name: test-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: push task
      uses: bingoYB/push-your-github@master
      with:
        ACCESS_TOKEN: teststring
        BRANCH: master