name: integration-tests
on: [push]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: push task
    #   uses: bingoYB/push-your-github@release-v1
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: master