name: integration-tests
on:
  schedule:
    - cron: 10 15 * * 0-6
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: push task
      uses: bingoYB/push-your-github@master
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master