name: integration-tests
on: 
  push:
    branches:
      - release-v1
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: push task
      uses: bingoYB/push-your-github@release-v1
      with:
        GITHUB_TOKEN: ${{ secrets.action_token }}
        BRANCH: master